# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/kamruljaman/Downloads/Chrome FDM/CPSC-453-Assignment-4-Demo-F25-main"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/kamruljaman/Downloads/Chrome FDM/CPSC-453-Assignment-4-Demo-F25-main/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"fmt-core\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/kamruljaman/Downloads/Chrome FDM/CPSC-453-Assignment-4-Demo-F25-main/build/CMakeFiles" "/Users/kamruljaman/Downloads/Chrome FDM/CPSC-453-Assignment-4-Demo-F25-main/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/kamruljaman/Downloads/Chrome FDM/CPSC-453-Assignment-4-Demo-F25-main/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImGui

# Build rule for target.
ImGui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImGui
.PHONY : ImGui

# fast build rule for target.
ImGui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/build
.PHONY : ImGui/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glad-opengl-3.3-core/CMakeFiles/glad.dir/build.make thirdparty/glad-opengl-3.3-core/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glfw-3.4/CMakeFiles/uninstall.dir/build.make thirdparty/glfw-3.4/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glfw-3.4/src/CMakeFiles/glfw.dir/build.make thirdparty/glfw-3.4/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glfw-3.4/src/CMakeFiles/update_mappings.dir/build.make thirdparty/glfw-3.4/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/fmt-11.2.0/CMakeFiles/fmt.dir/build.make thirdparty/fmt-11.2.0/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named 453-skeleton

# Build rule for target.
453-skeleton: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 453-skeleton
.PHONY : 453-skeleton

# fast build rule for target.
453-skeleton/fast:
	$(MAKE) $(MAKESILENT) -f 453-skeleton/CMakeFiles/453-skeleton.dir/build.make 453-skeleton/CMakeFiles/453-skeleton.dir/build
.PHONY : 453-skeleton/fast

#=============================================================================
# Target rules for targets named CPSC453-A4-Application

# Build rule for target.
CPSC453-A4-Application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CPSC453-A4-Application
.PHONY : CPSC453-A4-Application

# fast build rule for target.
CPSC453-A4-Application/fast:
	$(MAKE) $(MAKESILENT) -f application/CMakeFiles/CPSC453-A4-Application.dir/build.make application/CMakeFiles/CPSC453-A4-Application.dir/build
.PHONY : CPSC453-A4-Application/fast

thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.o: thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.o
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.o

# target to build an object file
thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.o
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.o

thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.i: thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.i
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.i
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.i

thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.s: thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.s
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.s
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.cpp.s

thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.o: thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.o
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.o

# target to build an object file
thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.o
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.o

thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.i: thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.i
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.i
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.i

thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.s: thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.s
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.s
.PHONY : thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.cpp.s

thirdparty/imgui-1.92.3/imgui.o: thirdparty/imgui-1.92.3/imgui.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui.o

# target to build an object file
thirdparty/imgui-1.92.3/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui.cpp.o

thirdparty/imgui-1.92.3/imgui.i: thirdparty/imgui-1.92.3/imgui.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui.cpp.i

thirdparty/imgui-1.92.3/imgui.s: thirdparty/imgui-1.92.3/imgui.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui.cpp.s

thirdparty/imgui-1.92.3/imgui_demo.o: thirdparty/imgui-1.92.3/imgui_demo.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_demo.o

# target to build an object file
thirdparty/imgui-1.92.3/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_demo.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_demo.cpp.o

thirdparty/imgui-1.92.3/imgui_demo.i: thirdparty/imgui-1.92.3/imgui_demo.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_demo.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_demo.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_demo.cpp.i

thirdparty/imgui-1.92.3/imgui_demo.s: thirdparty/imgui-1.92.3/imgui_demo.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_demo.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_demo.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_demo.cpp.s

thirdparty/imgui-1.92.3/imgui_draw.o: thirdparty/imgui-1.92.3/imgui_draw.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_draw.o

# target to build an object file
thirdparty/imgui-1.92.3/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_draw.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_draw.cpp.o

thirdparty/imgui-1.92.3/imgui_draw.i: thirdparty/imgui-1.92.3/imgui_draw.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_draw.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_draw.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_draw.cpp.i

thirdparty/imgui-1.92.3/imgui_draw.s: thirdparty/imgui-1.92.3/imgui_draw.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_draw.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_draw.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_draw.cpp.s

thirdparty/imgui-1.92.3/imgui_tables.o: thirdparty/imgui-1.92.3/imgui_tables.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_tables.o

# target to build an object file
thirdparty/imgui-1.92.3/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_tables.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_tables.cpp.o

thirdparty/imgui-1.92.3/imgui_tables.i: thirdparty/imgui-1.92.3/imgui_tables.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_tables.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_tables.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_tables.cpp.i

thirdparty/imgui-1.92.3/imgui_tables.s: thirdparty/imgui-1.92.3/imgui_tables.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_tables.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_tables.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_tables.cpp.s

thirdparty/imgui-1.92.3/imgui_widgets.o: thirdparty/imgui-1.92.3/imgui_widgets.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_widgets.o

# target to build an object file
thirdparty/imgui-1.92.3/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_widgets.cpp.o
.PHONY : thirdparty/imgui-1.92.3/imgui_widgets.cpp.o

thirdparty/imgui-1.92.3/imgui_widgets.i: thirdparty/imgui-1.92.3/imgui_widgets.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_widgets.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_widgets.cpp.i
.PHONY : thirdparty/imgui-1.92.3/imgui_widgets.cpp.i

thirdparty/imgui-1.92.3/imgui_widgets.s: thirdparty/imgui-1.92.3/imgui_widgets.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_widgets.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/imgui_widgets.cpp.s
.PHONY : thirdparty/imgui-1.92.3/imgui_widgets.cpp.s

thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.o: thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.o
.PHONY : thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.o

# target to build an object file
thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.o
.PHONY : thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.o

thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.i: thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.i
.PHONY : thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.i

# target to preprocess a source file
thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.i
.PHONY : thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.i

thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.s: thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.s
.PHONY : thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.s

# target to generate assembly for a file
thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.s
.PHONY : thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... 453-skeleton"
	@echo "... CPSC453-A4-Application"
	@echo "... ImGui"
	@echo "... fmt"
	@echo "... glad"
	@echo "... glfw"
	@echo "... thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.o"
	@echo "... thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.i"
	@echo "... thirdparty/imgui-1.92.3/backends/imgui_impl_glfw.s"
	@echo "... thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.o"
	@echo "... thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.i"
	@echo "... thirdparty/imgui-1.92.3/backends/imgui_impl_opengl3.s"
	@echo "... thirdparty/imgui-1.92.3/imgui.o"
	@echo "... thirdparty/imgui-1.92.3/imgui.i"
	@echo "... thirdparty/imgui-1.92.3/imgui.s"
	@echo "... thirdparty/imgui-1.92.3/imgui_demo.o"
	@echo "... thirdparty/imgui-1.92.3/imgui_demo.i"
	@echo "... thirdparty/imgui-1.92.3/imgui_demo.s"
	@echo "... thirdparty/imgui-1.92.3/imgui_draw.o"
	@echo "... thirdparty/imgui-1.92.3/imgui_draw.i"
	@echo "... thirdparty/imgui-1.92.3/imgui_draw.s"
	@echo "... thirdparty/imgui-1.92.3/imgui_tables.o"
	@echo "... thirdparty/imgui-1.92.3/imgui_tables.i"
	@echo "... thirdparty/imgui-1.92.3/imgui_tables.s"
	@echo "... thirdparty/imgui-1.92.3/imgui_widgets.o"
	@echo "... thirdparty/imgui-1.92.3/imgui_widgets.i"
	@echo "... thirdparty/imgui-1.92.3/imgui_widgets.s"
	@echo "... thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.o"
	@echo "... thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.i"
	@echo "... thirdparty/imgui-1.92.3/misc/cpp/imgui_stdlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

